# Machine Learning KNN assignments
### Ex 1. Data:



In [2]:
import pandas as pd
import numpy as np

In [4]:
# 1. Download the census data file from UCI Machine Learning repository 

habe = pd.read_csv('d://haberman.csv')
habe.head()

30  64   1  1.1
0  30  62   3    1
1  30  65   0    1
2  31  59   2    1
3  31  65   4    1
4  33  58  10    1

In [6]:
column_names = ['age', 'year', 'nodes', 'survival_status']
habe.columns = col_names
column_names

['age', 'year', 'nodes', 'survival_status']

In [7]:
habe.head()

age  year  nodes  survival_status
0   30    62      3                1
1   30    65      0                1
2   31    59      2                1
3   31    65      4                1
4   33    58     10                1

In [16]:
# Determine the independent variable

x = habe.drop(["survival_status"], axis = 1)
x.head()

age  year  nodes
0   30    62      3
1   30    65      0
2   31    59      2
3   31    65      4
4   33    58     10

In [17]:
# Determine the dependent variable
y = habe["survival_status"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: survival_status, dtype: int64

In [18]:
# Prepare the data file

habe.head()

age  year  nodes  survival_status
0   30    62      3                1
1   30    65      0                1
2   31    59      2                1
3   31    65      4                1
4   33    58     10                1

### Ex 2. Import relevant python libraries and sklearn KNN model

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20)

In [21]:
# Enable packages and syntax to scale data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

### Ex 4. Apply KNN algorithm 
### Ex 5. Train the model using the training set 

In [22]:
from sklearn.neighbors import KNeighborsClassifier

In [23]:
knn = KNeighborsClassifier (n_neighbors=4)

In [24]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [25]:
y_pred = knn.predict(x_test)
y_pred

array([1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1], dtype=int64)

### Ex 6. Predict using test data

In [26]:
knn.predict_proba(x_test)

array([[0.75, 0.25],
       [1.  , 0.  ],
       [0.75, 0.25],
       [0.75, 0.25],
       [0.25, 0.75],
       [0.75, 0.25],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.5 , 0.5 ],
       [1.  , 0.  ],
       [0.75, 0.25],
       [0.75, 0.25],
       [0.75, 0.25],
       [0.5 , 0.5 ],
       [1.  , 0.  ],
       [0.5 , 0.5 ],
       [0.75, 0.25],
       [0.25, 0.75],
       [1.  , 0.  ],
       [0.5 , 0.5 ],
       [1.  , 0.  ],
       [0.5 , 0.5 ],
       [0.75, 0.25],
       [0.5 , 0.5 ],
       [0.5 , 0.5 ],
       [0.5 , 0.5 ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.75, 0.25],
       [0.75, 0.25],
       [0.75, 0.25],
       [1.  , 0.  ],
       [0.75, 0.25],
       [0.75, 0.25],
       [0.5 , 0.5 ],
       [0.75, 0.25],
       [0.75, 0.25],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.5 , 0.5 ],
       [1.  , 0.  ],
       [0.75, 0.25],
       [0.  , 1.  ],
       [0.75, 0.25],
       [0.75, 0.25],
       [1.  , 0.  ],
       [0.75,

In [27]:
from sklearn.metrics import classification_report, confusion_matrix

In [28]:
# Prediction result matrix

print(confusion_matrix(y_test, y_pred))

[[43  3]
 [13  2]]


### Ex 7. Perform Accuracy check 


In [29]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.77      0.93      0.84        46
           2       0.40      0.13      0.20        15

    accuracy                           0.74        61
   macro avg       0.58      0.53      0.52        61
weighted avg       0.68      0.74      0.68        61

